FROM golang:1.25.1 AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY clientes/ ./clientes/
COPY shared/ ./shared/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o /out/app ./clientes/

FROM debian:bookworm-slim

# instala aplay
RUN apt-get update && apt-get install -y --no-install-recommends alsa-utils \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /out/app ./app
# copia o wav para dentro da imagem final
COPY clientes/jingle.wav ./clientes/jingle.wav

CMD ["./app"]