FROM golang:1.25.1 AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY atuadores/ ./atuadores/
COPY shared/ ./shared/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o /out/app ./atuadores/

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /out/app ./app

CMD ["./app"]